InfoTooltip reusable component
superdispatch/web-ui pull request #458
Opened 2023-03-07 09:30 UTC by umrzoq-toshkentov

2023-03-09 09:43 UTC, doniyor2109 requested changes

2023-03-09 10:14 UTC, umrzoq-toshkentov commented on packages/ui/src/info-tooltip/InfoTooltip.tsx
> +      const [isTooltipOpen, setIsTooltipOpen] = useState(false);
no need I will remove it and just paste some props for that

2023-03-09 10:17 UTC, umrzoq-toshkentov commented on packages/ui/src/info-tooltip/InfoTooltip.tsx
> +      const [isTooltipOpen, setIsTooltipOpen] = useState(false);
what about if I use useImparativeHandle for to connect with its ref?

2023-03-09 10:29 UTC, doniyor2109 commented on packages/ui/src/info-tooltip/InfoTooltip.tsx
> +      const [isTooltipOpen, setIsTooltipOpen] = useState(false);
@umrzoq-toshkentov Hmm, why do we need to connect with its ref?

2023-03-09 10:45 UTC, umrzoq-toshkentov commented on packages/ui/src/info-tooltip/InfoTooltip.tsx
> +      const [isTooltipOpen, setIsTooltipOpen] = useState(false);
yes we will connect with its ref e.g

```
const ParentComponent = () => {
   const ref = useRef<RefProps>(null)
   
   const onOpen = () => {
      //if you want can pass props and also can connect with two data binding 
      ref.current.openTooltip()
   }
   
   return (
     <Infotooltip ref={ref} />
   )
}
```

2023-03-09 10:49 UTC, umrzoq-toshkentov commented on packages/ui/src/info-tooltip/InfoTooltip.tsx
> +      const [isTooltipOpen, setIsTooltipOpen] = useState(false);
first of all it avoids from re-render and gives access to create own reusable component life cycle which is performant. We can easily connect child component with parent component and can utilize two-way data binding.

2023-03-09 10:55 UTC, doniyor2109 commented on packages/ui/src/info-tooltip/InfoTooltip.tsx
> +      const [isTooltipOpen, setIsTooltipOpen] = useState(false);
@umrzoq-toshkentov I think it is easier to control by props

2023-03-09 11:00 UTC, umrzoq-toshkentov commented on packages/ui/src/info-tooltip/InfoTooltip.tsx
> +      const [isTooltipOpen, setIsTooltipOpen] = useState(false);
okay I will change to props

2023-03-09 11:07 UTC, umrzoq-toshkentov commented on packages/ui/src/info-tooltip/InfoTooltip.tsx
> +      const [isTooltipOpen, setIsTooltipOpen] = useState(false);
updated to props

2023-03-10 05:34 UTC, doniyor2109 approved these changes

2023-03-10 05:38 UTC, normurod72 approved these changes

2023-03-10 06:01 UTC, merged