feat: [FRONT-58] added empty error message props for textfield
superdispatch/web-ui pull request #463
Opened 2023-05-10 11:57 UTC by umrzoq-toshkentov

While on this case I need to make red border textfield on error time, but I do not want to return any message
<img width="1511" alt="image" src="https://github.com/superdispatch/web-ui/assets/118124821/c2f58966-84d1-49ce-8fbb-59414e98deb6">

2023-05-10 12:59 UTC, doniyor2109 commented
@umrzoq-toshkentov Can you make something like this?

https://github.com/superdispatch/web-ui/blob/0fcf8f6f3e87c2e153ecf93dc3e3fe64e9dd333c/packages/forms/src/text/FormikCurrencyField.tsx#L10

2023-05-10 13:05 UTC, normurod72 commented on packages/forms/src/text/FormikTextField.tsx
> +          helperText={!emptyErrorMessage && (errorText || helperText)}
@umrzoq-toshkentov I think we can also not render helperText content when null or empty string provided, what do you think?

2023-05-10 13:13 UTC, umrzoq-toshkentov commented on packages/forms/src/text/FormikTextField.tsx
> +          helperText={!emptyErrorMessage && (errorText || helperText)}
@timurhamitov I think I will remove this errorProps. I will use `EMPTY_ERROR_MESSAGE`. thanks to @doniyor2109

2023-05-10 13:52 UTC, normurod72 approved these changes

2023-05-10 19:34 UTC, umrzoq-toshkentov commented on packages/forms/src/text/FormikTextField.tsx
> +import { EMPTY_ERROR_MESSAGE } from './FormikCurrencyField';
created constants file and exported there

2023-05-11 07:29 UTC, doniyor2109 requested changes

2023-05-11 07:29 UTC, doniyor2109 commented on packages/forms/src/__tests__/index.spec.ts
> -      "EMPTY_ERROR_MESSAGE": "EMPTY_ERROR_MESSAGE",
@umrzoq-toshkentov We should not remove this constant from public APIs. Can you re export it?

2023-05-11 07:35 UTC, doniyor2109 commented on packages/forms/src/__tests__/index.spec.ts
> -      "EMPTY_ERROR_MESSAGE": "EMPTY_ERROR_MESSAGE",
Let's include constayfile in index.ts file

2023-05-11 08:20 UTC, doniyor2109 approved these changes

2023-05-11 08:20 UTC, merged