feat: [CAR-4764] Made overrides templates
superdispatch/web-ui pull request #466
Opened 2023-07-27 00:21 UTC by TravnikovDev

2023-07-27 11:39 UTC, TravnikovDev commented on package.json
> +    "plop": "^3.1.2",
Updated

2023-07-27 11:39 UTC, TravnikovDev commented on plop-templates/README.hbs
Moved

2023-07-27 12:47 UTC, timurhamitov approved these changes

2023-07-28 06:56 UTC, doniyor2109 requested changes

2023-07-28 06:56 UTC, doniyor2109 commented on scripts/plop-templates/customHook.hbs
Do we use it somewhere?

2023-07-28 06:56 UTC, doniyor2109 commented on scripts/plop-templates/lab-component/component.hbs
> +);
Can we add displayName as well?

2023-07-28 08:31 UTC, TravnikovDev commented on scripts/plop-templates/lab-component/component.hbs
> +);
Added

2023-07-28 08:31 UTC, TravnikovDev commented on scripts/plop-templates/customHook.hbs
It's just template. I've left it as a showcase. Maybe someone will extend it in future

2023-07-28 09:06 UTC, doniyor2109 commented on scripts/plop-templates/customHook.hbs
@TravnikovDev Lets remove it for now.

2023-07-28 09:30 UTC, doniyor2109 approved these changes

2023-07-28 09:31 UTC, merged